version: "3.0"
services:
  es:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9300:9300
    networks:
      - es-net
  app:
    container_name: application
    image: food:1.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - es
    # ports:
    #   - 8083:5000
    networks:
      - nginx-net
      - es-net
  ngnix:
    container_name: meta-nginx
    image: nginx:stable-alpine
    networks:
      - nginx-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/usr/share/nginx/html
      - ./static:/usr/share/nginx/html/static
    ports:
      - 8080:80


networks:
    es-net:
      driver: bridge
    nginx-net:
      driver: bridge

